name: Build and Deploy Vite App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Set Environment Variables
        run: |
          echo "VITE_LOGIN_API_URL=${{ secrets.VITE_LOGIN_API_URL }}" >> $GITHUB_ENV
          echo "VITE_REGISTRATION_API_URL=${{ secrets.VITE_REGISTRATION_API_URL }}" >> $GITHUB_ENV

      - name: Debug ENV Variables
        run: |
          echo "LOGIN API URL: $VITE_LOGIN_API_URL"
          echo "REGISTRATION API URL: $VITE_REGISTRATION_API_URL"

      - name: Build Vite App
        run: npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_SAND_05B936500 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/app"
          api_location: "api"
          output_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
