name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Node 20으로 업그레이드
          cache: 'npm'
          cache-dependency-path: ./app/package-lock.json
      - name: Create .env.production file
        run: |
          echo "VITE_LOGIN_API_URL=${{ secrets.VITE_LOGIN_API_URL }}" > .env.production
          echo "VITE_REGISTRATION_API_URL=${{ secrets.VITE_REGISTRATION_API_URL }}" >> .env.production
        working-directory: ./app
      - name: Debug .env.production
        run: cat ./app/.env.production
      - name: Clear npm cache
        run: npm cache clean --force
        working-directory: ./app
      - name: Install Dependencies
        run: npm ci  # package-lock.json 필요
        working-directory: ./app
      - name: Build Vite App
        run: npm run build
        working-directory: ./app
      - name: Debug Build Output
        run: ls -la ./app/dist
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_SAND_05B936500 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/app"
          api_location: ""
          output_location: "dist"
          skip_app_build: true  # Azure의 추가 빌드 스킵
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_SAND_05B936500 }}
          action: "close"
