name: React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 코드 체크아웃
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      # Step 2: Node.js 설정
      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Step 3: Docker Hub 로그인
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: DOCKER_USERNAME 검증
      - name: DOCKER_USERNAME 확인
        run: |
          echo "DOCKER_USERNAME is set to: ${{ secrets.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "오류: DOCKER_USERNAME이 비어 있거나 설정되지 않았습니다. GitHub 저장소 설정에서 DOCKER_USERNAME 비밀을 설정하세요."
            exit 1
          fi
          if ! echo "${{ secrets.DOCKER_USERNAME }}" | grep -qE '^[a-zA-Z0-9_-]+$'; then
            echo "오류: DOCKER_USERNAME에 유효하지 않은 문자가 포함되어 있습니다. 영숫자, 밑줄, 하이픈만 사용 가능합니다."
            exit 1
          fi

      # Step 5: Docker 이미지 빌드 및 푸시
      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/react_image:latest
          build-args: |
            VITE_LOGIN_API_URL=${{ secrets.VITE_LOGIN_API_URL }}
            VITE_REGISTRATION_API_URL=${{ secrets.VITE_REGISTRATION_API_URL }}
        env:
          DOCKER_BUILDKIT: 1

      # Step 6: 빌드 인자 및 태그 디버깅
      - name: 빌드 인자 및 태그 확인
        run: |
          echo "사용된 빌드 인자:"
          echo "VITE_LOGIN_API_URL=${{ secrets.VITE_LOGIN_API_URL }}"
          echo "VITE_REGISTRATION_API_URL=${{ secrets.VITE_REGISTRATION_API_URL }}"
          echo "Docker 태그: ${{ secrets.DOCKER_USERNAME }}/react_image:latest"

      # Step 7: SSH 설정 확인
      - name: SSH 설정 확인
        run: |
          echo "SSH_HOST is set to: ${{ secrets.SSH_HOST }}"
          echo "SSH_USER is set to: ${{ secrets.SSH_USER }}"
          echo "SSH_PORT is set to: ${{ secrets.SSH_PORT }}"
          echo "SSH_PASSWORD is set: ${{ secrets.SSH_PASSWORD != '' }}"
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "오류: SSH_HOST가 비어 있거나 설정되지 않았습니다."
            exit 1
          fi
          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "오류: SSH_USER가 비어 있거나 설정되지 않았습니다."
            exit 1
          fi
          if [ -z "${{ secrets.SSH_PASSWORD }}" ]; then
            echo "오류: SSH_PASSWORD가 비어 있거나 설정되지 않았습니다."
            exit 1
          fi
          if [ -z "${{ secrets.SSH_PORT }}" ]; then
            echo "오류: SSH_PORT가 비어 있거나 설정되지 않았습니다. 기본값 22를 사용하려면 22로 설정하세요."
            exit 1
          fi

      # Step 8: 서버 배포
      - name: 서버 배포
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} '
            # Docker Hub 로그인
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # 기존 컨테이너 중지 및 제거
            docker stop react_image || true
            docker rm react_image || true
            # 최신 이미지 풀
            docker pull ${{ secrets.DOCKER_USERNAME }}/react_image:latest
            # Docker 네트워크 확인 및 생성
            docker network create app-network || true
            # 새 컨테이너 실행
            docker run -d --name react_image \
              --network app-network \
              -p 300:3000 \
              -e VITE_LOGIN_API_URL=${{ secrets.VITE_LOGIN_API_URL }} \
              -e VITE_REGISTRATION_API_URL=${{ secrets.VITE_REGISTRATION_API_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/react_image:latest
          '
